name: Checkov Checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v2
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload Serif File
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif
